-
  - { name: wam_position, required: true }
  - { name: wam_torque, required: true }
  - { name: bh_movehand }
-
  - { name: wam_position, required: true }
  - { name: wam_torque, required: true }
  - { name: bh_position, required: true }
-
  - { name: wam_position, required: true }
  - { name: wam_torque, required: true }
  - { name: bh_movehand }
-
  - { name: wam_position, required: true }
  - { name: wam_torque, required: true }
  - { name: bh_position, required: true }
